spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8888