server:
  port: 8082

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/tasks_db?createDatabaseIfNotExist=true
    username: springstudent
    password: springstudent
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/