eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defautltZone: http://localhost:8761/eureka
server:
  port: 8081
spring:
  application:
    name: ressources
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ressources
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: db/megration
    baseline-on-migrate: true